# Generated by Django 4.2.2 on 2024-05-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0002_artist_user"),
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="artists.artist",
            ),
        ),
    ]
